### ISSUE TITLE
DLNA support

### ISSUE THREAD

**Issue by JeppeTh** [fuzeman/Spotify2.bundle#2]
I haven't investigated yet what the reason is but my DLNA clients doesn't seem to be able to play anything. Sometimes the first song of an album works - but not the rest...

**Comment by kaohlive** [comment]
I confirm this, I also am able to play A song per album it seems.
On plex clients they all work, but using Dlna most fail.

**Comment by fuzeman** [comment]
You can try out the latest beta (v0.5.2) for a fix now. Streaming is working properly on the latest XBMC (beta) and a Sony Bravia (2012) TV now.

If you still find an issue, let me know which client you are using for DLNA, the bug you are seeing could be specific to that client.

**Comment by JeppeTh** [comment]
I have made some test and it seems the most stable variant so far. Some things
- It takes 10 seconds between tracks. If proxy is turned off it can't play at all. Have proxy always been used in prior releases? Don't know if it was a prior beta - or the currently stable relase that it was a lot faster - like 1-3 seconds or similar. So at least something got worse in this beta than it has been.
- pause and seeking doesn't really work. Most often it skips to next track.
  This has mostly been tested with my Integra(Onkyo) amplifier. Perhaps my android clients handles it better - but I believe BubbleUPnP migh perhaps buffer tracks and so on...
- Large playlist returns 0 tracks - but seems to be genereal - not only DLNA.

But the previous faults with same song playing, buffering, playback stopping and so on seems to be fixed!

I'll post you some logs.

**Comment by JeppeTh** [comment]
I also tried my Samung it manages DLNA pretty good I must say, like 1 seconds between tracks. Even better than Samsung Plex Client!
But personally I would prefer if it worked better with my Integra amplifier...

**Comment by fuzeman** [comment]
I can roughly see what might be causing this, the device seems to be firing off a number of requests (around 8 per track), these requests are resulting in the same track being downloaded multiple times before even starting to play.

I'll need to make the streaming server understand this case a bit better and ensure the track is only downloaded once and streamed out as it's received.

---

The stable release uses a method of streaming which can be unreliable at times and it wasn't possible to adjust the User-Agent on requests.

**Comment by JeppeTh** [comment]
Ok,  great that there's hope to improve it.  I wonder why the client behaves like that... Sounds strange,  would make sense if it doesn't like the responses and then retries. But if all are equal,  then it wouldn't like last response either. Just to  double check, the case you're looking at isn't a case with proxy off (which I noticed wasn't implemented yet)?

**Comment by fuzeman** [comment]
Could you try the 'develop' version out now ([develop.zip](https://github.com/fuzeman/Spotify2.bundle/archive/develop.zip))? I've made a number of changes which means we re-use existing stream buffers more, only opening a new stream when the end frames are requested.

I can't really test your exact case, so provide the plugin + Plex DLNA server logs if there is still a problem.

---

The requests being sent do kinda make sense, it's basically downloading the track in multiple parts (to try receive it faster), the streaming server just didn't handle this too well...

**Comment by JeppeTh** [comment]
I'll try to tomorrow. Btw -.sometimes old spotify isn't possible to remove since

...Plex Media Server\Plug-ins\Spotify2.bundle\Contents\Libraries\Shared\cherrypy\wsgiserver\wsgiserver2.py

it's used by some process...

**Comment by JeppeTh** [comment]
Ran some quick tests and it works a lot better.  Seeking and pause seems to work. And initial song started in a second. However skipping to next tack still required long time before starting.  I'll provide a log later on.

**Comment by fuzeman** [comment]
Yeah, there seems to be a couple of small bugs, will work on a fix now.

**Comment by fuzeman** [comment]
I've got a fix in the `develop` branch ([develop.zip](https://github.com/fuzeman/Spotify2.bundle/archive/develop.zip)), hopefully this solves the problem.

**Comment by JeppeTh** [comment]
Not really - never got the quick start. 6-10 seconds changing tracks. New logs on its way

**Comment by fuzeman** [comment]
There doesn't seem to be any obvious issues now, it looks like the device might be waiting for a number of requests to finish before starting to play, so we can really only try optimize streaming/buffering to speed up these requests.

I've made a few improvements which were slowing things down a bit (in the `develop` branch now), but I'm not sure how much difference this would make.

I've also just implemented the old streaming method (from the `master` branch), so you could try disabling "Streaming Server" (in plugin settings). I would be interested in how fast this is in comparison, it does have it's own issues though (random stream failures, seeking issues).

**Comment by JeppeTh** [comment]
This version was worse - 10-11 seconds between songs. Then plyaback failed (however I got network glitch afterwards - so perhaps that's why it failed to play.

When I turned off streaming server I couldn't even browse playlists etc. I.e. no songs to play.

I wonder which release this was
https://forums.plex.tv/index.php/topic/107169-rel-spotify2/?view=findpost&p=638527
I will try to find out and give you logs for that one - then perhaps you can compare...
I guess perhaps it was this release.
https://github.com/fuzeman/Spotify2.bundle/tree/feature/server-streaming

**Comment by fuzeman** [comment]
According to the logs heaps of tracks were being skipped (~40 were skipped) because Spotify was refusing to open streams, this is a result of using the incorrect track for your country (there are sometimes multiple versions of the same track for specific countries).

I'll get a fix for this issue and an error in the streaming server that still seems to be happening (not sure if this effecting the speed of streaming).

---

Was that `feature/server-streaming` release faster for streaming on this device? because there is definitely a big difference in how that streaming worked.

We could possibly detect the client and switch streaming modes if that is the case.

**Comment by JeppeTh** [comment]
I'll try to test other version later today.  Noticed that version also had configuration option for pms proxy. Perhaps config isn't used in that version? It seemed proxy was disabled after installation though. Perhaps that's why it was fast

 But first let me try it out again.

**Comment by JeppeTh** [comment]
It seems this old version is lacking the logon fix - i.e. login fails with it...

**Comment by fuzeman** [comment]
Ah, forgot about that. I'll try get that branch working again now.

**Comment by fuzeman** [comment]
The `feature/server-streaming` branch is working again

---

**EDIT** - there is also couple more fixes in the `develop` branch now.

**Comment by fuzeman** [comment]
2 - 3 seconds delay is normal at this stage. I'm planning on switching HTTP libraries (to a lower-level C library) in the future, this should bring the delay down a bit more.

Just pushed some changes to the `develop` branch which should automatically switch streaming "modes" when it detects the `INTEGRA DTR-40.2` client profile.

Let me know the results of these changes.

**Comment by JeppeTh** [comment]
Hm, apart from fairly quick start that streaming mode doesn't work well on the feature branch. Buffering and aborting if you rember. Is that supposed to work better on develop branch with that same streaming mode? 

And is there a reasonable explanation for the different delays between the modes? 

Also,  perhaps it should be configurable to specify which clients that should use other mode.

**Comment by fuzeman** [comment]
Yeah, there were a number of other problems which caused that (buffering, aborting).

Calling it a "mode" probably isn't the correct term, we are just disabling certain features in the (newer) streaming server, so you still get all the changes which fixed the buffering/aborting issues.

---

At this stage, I believe the device might not have a good implementation of the HTTP `Range` requests and is waiting on the entire track to be buffered before playing it (causing a long delay).

Disabling the support for `Range` requests on the streaming server might be causing the device to fallback to a streaming system that can properly play a track while continuing to buffer.

---

We have streaming profiles which allow client-specific settings now, these are located here https://github.com/fuzeman/Spotify2.bundle/tree/develop/Contents/Profiles

So, this `Range` feature can be disabled on other clients if needed.

**Comment by JeppeTh** [comment]
Can't play a single song...

**Comment by fuzeman** [comment]
Looks like this is what started causing the issues

```
[plugin.stream] Request failed: HTTPConnectionPool(host='dsu0uct5x2puz.cloudfront.net', port=80): Max retries exceeded with url: /mp3/[...].mp3 (Caused by <class 'socket.gaierror'>: [Errno 11001] getaddrinfo failed)
```

This caused the streaming server to get stuck in a bad state, so every stream after that failed. Probably just a random network issue, so restarting PMS might get it working again.

I'll work on a fix to make sure it can't get stuck though.

**Comment by fuzeman** [comment]
That bug should be fixed with the latest changes on the develop branch.

**Comment by JeppeTh** [comment]
Tried again and now I get a quick start when enable streaming server - less than 3 secs I believe (disabling server I got like 13 seconds instead?!??!).
However - I still see the hanging at 52 seconds and aborting/stopping at 58 seconds...

Also seeking doesn't work - when you disable range it sounds like range HTTP headers are disabled or similar - does it mean seeking is disabled as well?

Can the 8 requests per track be caused by that your server doesn't respond to range requests in an acceptable way? Perhaps the total content length is unknown - and that causes troubles?

BTW - how's it going with truncated playlists? It doesn't seem to work for me at least...

New logs will be sent later

**Comment by fuzeman** [comment]
It seems to just suddenly stop streaming at ~10% for some reason, guessing this would roughly match where it stops at ~58 seconds.

```
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [|                    ] 000%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0] Streaming [|                    ] 000%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0] Streaming [|                    ] 000%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0] Streaming [|                    ] 000%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [ |                   ] 005%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0] Streaming [ |                   ] 005%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [  |                  ] 010%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0] Streaming [  |                  ] 010%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [   |                 ] 015%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [    |                ] 020%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [     |               ] 025%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [      |              ] 030%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [       |             ] 035%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [        |            ] 040%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [         |           ] 045%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [          |          ] 050%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [           |         ] 055%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [            |        ] 060%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [             |       ] 065%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [              |      ] 070%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [               |     ] 075%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [                |    ] 080%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [                 |   ] 085%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [                  |  ] 090%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [                   | ] 095%
[plugin.util] [spotify:track:1Ba0dzWGSyKQ5QlvSUdAhQ] [0]   Reading [                    |] 100%
```

I'll try reproduce the issue and figure out what's happening.

---

Direct streaming (when the streaming server disabled) is very buggy due to limitations with how it works. It's possibly going to be removed again.

---

Seeking should be possible, but it's really up to how the client supports it. I'm wondering if it's related to this error in the latest log file:

```
[Errno 10055] An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.
```

Will need to research this error a bit more.

---

The server now receives 3 requests when a stream is started, this would simply be a way of receiving the track faster.

The HTTP spec allows servers to indicate they have no "Range" header support and should fallback correctly, so there shouldn't be any problem doing this.

---

There was a bug awhile back that broke truncated playlists, but this should be fixed now.

Could you send me a log showing this? maybe something else is causing this...

**Comment by fuzeman** [comment]
Possible fix is on the develop branch now, it might actually fix both bugs (stopping at 58s, seeking).

Still might need to tweak the value a bit, but we will see what happens first.

**Comment by JeppeTh** [comment]
No difference

**Comment by fuzeman** [comment]
Hmm, haven't been able to reproduce the issue, so this might be a bit difficult to fix. I've found (and fixed) a couple of problems with streaming, but I'm not really sure these were related to the issue you were finding.

Could you update to the 'develop' branch again (as there is more information logged for debugging now) and provide both the plugin and "Plex DLNA Server.log" files after trying to stream again.

I'll also start up a VM later today to try reproduce this on Windows XP, it might be an issue specific to that platform...

---

**Edit** - I've bumped up the timeout on playing loading as well, so large playlists should load now. The speed of playlist loading might be a problem though...

**Comment by fuzeman** [comment]
It looks like the "Plex DLNA Server" is forcing the range support header to be sent to the client, so the client is probably stopping the stream after it fails to receive the correct range.

Disabling range support actually causes XBMC to only play a few seconds before stopping the track.

---

Looking back at possible issues having multiple streams open (when "range" support is enabled), I noticed we weren't closing the response properly so streams could be delayed until the entire track was buffered.

This sounds quite likely to be issue that was causing the long delays (the 6 - 10 seconds between tracks) when we had "range" support enabled.

---

So, on the develop branch I should have everything setup to test "range" support again, with the (possible) fix in place.

I've also made some changes to logging, with these new options added:
![](http://i.imgur.com/BcHomt7.png)
Using these values for the options will provide mountains of more detail if there are any streaming/buffering issues.

**Note** - Enabling "TRACE" mode could impact performance, so try stream without it first.
